name: Build Test
on: [push]
jobs:
  build-shim:
    strategy:
      matrix:
        platform: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Context for Buildx
        run: docker context create builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builder
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: "${{ runner.os }}-${{ matrix.platform }}-buildx-${{ github.sha }}"
          restore-keys: "${{ runner.os }}-${{ matrix.platform }}-buildx-"
      - run: mkdir -p "./work/output/${{ matrix.platform }}"
      - name: Build
        uses: docker/build-push-action@v2
        with:
          platforms: "linux/${{ matrix.platform }}"
          context: .
          file: "test/Dockerfile"
          cache-from: "type=local,src=/tmp/.buildx-cache"
          cache-to: "type=local,mode=max,dest=/tmp/.buildx-cache-new"
          outputs: "type=local,dest=./work/output/${{ matrix.platform }}"
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
